# frozen_string_literal: true

# This file was generated by the `rails generate rspec:install` command.
# It is customized for use within a Rails Engine.
#
# The specs run in the application context, so Rails environment is typically loaded
# via `rails_helper.rb`. This file contains options that are not specific to Rails.

RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library, such as MiniTest::Assertions, provided that
  # the library is compatible with the spec framework.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include details about the provided
    # object — e.g., `is expected to equal 1` would become `expected "2" to equal 1`.
    # `true` may be more generally useful:
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `true` in RSpec 4. It makes the `description`
  # and `failure_message` of custom matchers include details about the provided
  # object — e.g., `is expected to equal 1` would become `expected "2" to equal 1`.
  # `true` may be more generally useful:
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When running RSpec
  # with the `--order random` command line option and this setting set to
  # `true`, this will cause the specs to run in a random order.
  # The default behavior is to run specs with matching tags first, then
  # run all other specs in the default order (e.g. roughly the order they
  # were defined in).
  # config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to speed up
  # the specs that are running. This is useful for large test suites that
  # may take a long time to run.
  #
  # If you don't use this, you'll need to turn it off completely:
  # config.example_status_persistence_file_path = "spec/examples.txt"

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface where the specs are slowing down.
  # You can customize this to whatever number you like.
  # config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, like this:
  #   `--seed 12345`
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # We use the same seed in the test suite to ensure that tests are always
  # run in the same order, regardless of the order they are defined.
  Kernel.srand config.seed
end
